vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    users:
      uri_prefix: /images/users
      upload_destination: '%kernel.project_dir%/public/images/users'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    creator:
      uri_prefix: /images/creator          # <-- fixed (was /images/athlete)
      upload_destination: '%kernel.project_dir%/public/images/creator'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    athlete:
      uri_prefix: /images/athlete
      upload_destination: '%kernel.project_dir%/public/images/athlete'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    media_assets:
      uri_prefix: /uploads/media
      upload_destination: '%kernel.project_dir%/public/uploads/media'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
